baseURL = 'https://someonesay.it'
languageCode = 'zh-cn'
title = '某人说'
theme = "yinyang"
DefaultContentLanguage = "cn"
googleAnalytics = 'G-NVDR5V5Y7P'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    guessSyntax = true
    noClasses = true
    style = "bw"
    tabWidth = 2

[author]
  name = "某人"
  homepage = "https://someonesay.it"

[params]
headTitle = "SomeOneSayIt"
mainSections = ["posts"]

[[params.socials]]
name = "About Me"
link = "https://www.someonesay.it/pages/about"
