baseURL = 'https://someonesay.it'
languageCode = 'zh-cn'
title = '某人说'
theme = "yinyang"
DefaultContentLanguage = "cn"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    guessSyntax = true
    noClasses = true
    style = "bw"
    tabWidth = 2

[author]
  name = "某人"
  homepage = "https://someonesay.it"

[params]
headTitle = "SomeOneSayIt"
mainSections = ["posts"]
extraHead = "<script async src='https://www.googletagmanager.com/gtag/js?id=G-NVDR5V5Y7P'></script><script>  window.dataLayer = window.dataLayer || [];  function gtag(){dataLayer.push(arguments);}  gtag('js', new Date());  gtag('config', 'G-NVDR5V5Y7P');</script>"

[[params.socials]]
name = "About Me"
link = "https://www.someonesay.it/pages/about"

